### ISSUE TITLE
Problems installing on Nodejs 7.4

### ISSUE THREAD

**Issue by orgertot** [punkave/mechanic#5]
Hi,
I cannot get mechanic running on nodejs 7.4. I dont know if that is supported or what?

This is my error code:
```
node@architectofweb:~$ sudo npm install mechanic -g
/usr/local/nvm/v7.4.0/bin/mechanic -> /usr/local/nvm/v7.4.0/lib/node_modules/mechanic/bin/mechanic

> fs-ext@0.5.0 install /usr/local/nvm/v7.4.0/lib/node_modules/mechanic/node_modules/fs-ext
> node-gyp configure build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/nvm/v7.4.0/lib/node_modules/mechanic/node_modules/fs-ext/.node-gyp"
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/local/nvm/v7.4.0/bin/node" "/usr/local/nvm/v7.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/nvm/v7.4.0/lib/node_modules/mechanic/node_modules/fs-ext
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/local/nvm/v7.4.0/lib
âââ (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/mechanic/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/nvm/v7.4.0/bin/node" "/usr/local/bin/npm" "install" "mechanic" "-g"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! fs-ext@0.5.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-ext@0.5.0 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fs-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fs-ext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fs-ext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
```

I already tried all the things i can imagine to fix it..

Thanks

**Comment by boutell** [comment]
This module includes some C++ code, which requires that a compiler toolchain be installed on your system. The error about "make" not being found is the giveaway.

C++ code is unavoidable because the `prettiest` module must use `flock` to prevent copies of the script from executing simultaneously, damaging the database, and the nodejs core team, in their infinite wisdom, have not included `flock` or an equivalent so far.
